import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <nav className="flex py-3 items-center justify-between bg-yellow-700 px-6" >
           <Link href = "/"  className="cursor-pointer py-2 px-4 text-xl bg-slate-700 text-white rounded-lg"> Home </Link>
           <Link href = "/posts"  className="cursor-pointer py-2 px-4 text-xl bg-slate-700 text-white rounded-lg"> Posts </Link>
           <Link href = "/articles" className="cursor-pointer py-2 px-4 text-xl bg-slate-700 text-white rounded-lg" > Articles </Link>
        </nav>
       <div className="px-6" >
        
         {children}
       </div>
      </body>
    </html>
  );
}
